#include <bits/stdc++.h>
using namespace std;

const long long MOD = 1000000007;

void solve(long long K){

}

// Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long K;
    scanf("%lld",&K);
    solve(K);
    return 0;
}
