#include <bits/stdc++.h>
using namespace std;


void solve(long long T, long long L, long long X, long long Y, long long Q, std::vector<long long> E){

}

// Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long T;
    scanf("%lld",&T);
    long long L;
    scanf("%lld",&L);
    long long X;
    scanf("%lld",&X);
    long long Y;
    scanf("%lld",&Y);
    long long Q;
    scanf("%lld",&Q);
    std::vector<long long> E(Q);
    for(int i = 0 ; i < Q ; i++){
        scanf("%lld",&E[i]);
    }
    solve(T, L, X, Y, Q, std::move(E));
    return 0;
}
