#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long B){

}

// Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long B;
    scanf("%lld",&B);
    solve(N, B);
    return 0;
}
