#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long a_x, long long a_y, long long b_x, long long b_y, long long c_x, long long c_y){

}

// Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long a_x;
    std::scanf("%lld", &a_x);
    long long a_y;
    std::scanf("%lld", &a_y);
    long long b_x;
    std::scanf("%lld", &b_x);
    long long b_y;
    std::scanf("%lld", &b_y);
    long long c_x;
    std::scanf("%lld", &c_x);
    long long c_y;
    std::scanf("%lld", &c_y);
    solve(a_x, a_y, b_x, b_y, c_x, c_y);
    return 0;
}
