#include <iostream>
#include <iomanip>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, std::vector<long long> P, std::vector<long long> Q){

    double ans = 0.0;
    for(int n = 1; n <= N; n++) {
        ans += (double) Q[n] / (double) P[n];
    }

    printf("%.6lf\n", ans);

}

// Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    std::vector<long long> P(N + 1);
    std::vector<long long> Q(N + 1);
    for(int i = 1 ; i <= N ; i++){
        std::scanf("%lld", &P[i]);
        std::scanf("%lld", &Q[i]);
    }
    solve(N, std::move(P), std::move(Q));
    return 0;
}
