#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long Q, std::vector<long long> x, std::vector<long long> y, std::vector<long long> q){

}

// Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long Q;
    scanf("%lld",&Q);
    std::vector<long long> x(N);
    std::vector<long long> y(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&x[i]);
        scanf("%lld",&y[i]);
    }
    std::vector<long long> q(Q);
    for(int i = 0 ; i < Q ; i++){
        scanf("%lld",&q[i]);
    }
    solve(N, Q, std::move(x), std::move(y), std::move(q));
    return 0;
}
