#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> P, long long Q, std::vector<long long> U, std::vector<long long> D){

}

// Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> P(N-2+1);
    for(int i = 0 ; i < N-2+1 ; i++){
        scanf("%lld",&P[i]);
    }
    long long Q;
    scanf("%lld",&Q);
    std::vector<long long> U(Q);
    std::vector<long long> D(Q);
    for(int i = 0 ; i < Q ; i++){
        scanf("%lld",&U[i]);
        scanf("%lld",&D[i]);
    }
    solve(N, std::move(P), Q, std::move(U), std::move(D));
    return 0;
}
