#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

bool isPrime(long long n) {
    for(int i = 2; i*i <= n; i++) {
        if(n % i == 0) return false;
    }
    return true;
}

void solve(long long N){
    vector<long long> prime_nums;
    for(int n = 2; n <= N; n++) {
        if(isPrime(n)) {
            prime_nums.push_back(n);
        }
    }

    for(int idx = 0; idx < prime_nums.size(); idx++) {
        if(idx != (prime_nums.size() - 1)) {
            cout << prime_nums[idx] << " ";
        } else {
            cout << prime_nums[idx] << endl;
        }
    }
}

// Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    solve(N);
    return 0;
}
