#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

long long calcConbination(long long n, long long r) {
    long long numerator = 1;
    long long denominator = 1;
    for(int i = r; i >= 1; i--){
        numerator *= n;
        denominator *= i;
        n--;
    }
    return numerator / denominator;
}

void solve(long long n, long long r){
    cout << calcConbination(n, r) << endl;
}

// Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long n;
    std::scanf("%lld", &n);
    long long r;
    std::scanf("%lld", &r);
    solve(n, r);
    return 0;
}
