#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
#include <iomanip>
using namespace std;


void solve(long long N, std::vector<long long> x, std::vector<long long> y){

    double ans = 2000000.0;
    for(int i = 0; i < N-1; i++) {
        for(int j = i+1; j < N; j++) {
            double d = sqrt(pow(x[i] - x[j], 2.0) + pow(y[i] - y[j], 2.0));
            if(d < ans) ans = d;
        }
    }

    cout << fixed << setprecision(15) << ans << endl;

}

// Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    std::vector<long long> x(N);
    std::vector<long long> y(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &x[i]);
        std::scanf("%lld", &y[i]);
    }
    solve(N, std::move(x), std::move(y));
    return 0;
}
