#include <bits/stdc++.h>
using namespace std;

const long long MOD = 1000000007;

void solve(long long N, long long B, long long K, std::vector<long long> c){

}

// Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long B;
    scanf("%lld",&B);
    long long K;
    scanf("%lld",&K);
    std::vector<long long> c(K);
    for(int i = 0 ; i < K ; i++){
        scanf("%lld",&c[i]);
    }
    solve(N, B, K, std::move(c));
    return 0;
}
