#include <bits/stdc++.h>
using namespace std;


void solve(long long H, long long W, long long N, std::vector<long long> A, std::vector<long long> B, std::vector<long long> C, std::vector<long long> D){

}

// Generated by 2.2.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long H;
    scanf("%lld",&H);
    long long W;
    scanf("%lld",&W);
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    std::vector<long long> B(N);
    std::vector<long long> C(N);
    std::vector<long long> D(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
        scanf("%lld",&B[i]);
        scanf("%lld",&C[i]);
        scanf("%lld",&D[i]);
    }
    solve(H, W, N, std::move(A), std::move(B), std::move(C), std::move(D));
    return 0;
}
